### ISSUE TITLE
league/flysystem 版本问题

### ISSUE THREAD

**Issue by imnpc** [calchen/flysystem-aliyun-oss#1]
原参考是"league/flysystem": "~1.0", 安装没问题，
但是当前包内是1.0.53,在Laravel 6 下有问题  报错

**Comment by calchen** [comment]
我会确认的，然后具体能提供一下你所用的 Laravel 版本嘛？

**Comment by imnpc** [comment]
> 我会确认的，然后具体能提供一下你所用的 Laravel 版本嘛？

Laravel version | 6.20.11

我自己临时改了下 可以安装

**Comment by calchen** [comment]
刚刚放宽了 league/flysystem 依赖要求，可以试一下～感谢反馈
